version: '3.8'

services:
  db:
    image: postgres:15
    container_name: maturity_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maturity_classifier
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: maturity_backend
    depends_on:
      - db
    ports:
      - "8000:8000"